extends:
- plugin:prettier/recommended

plugins:
  - import

rules:
  curly: error
  import/no-extraneous-dependencies:
  - error
  - devDependencies: ["tests*/**"]
  no-else-return: error
  prefer-const: error
  prefer-arrow-callback: error
  strict: error
  no-useless-ternary: error
  no-max-len: 0
