extends: prettier

plugins:
  - prettier
  - import

rules:
  prettier/prettier: ["error"]
  import/no-extraneous-dependencies: ["off"]
  no-else-return: error
  prefer-const: error
  prefer-arrow-callback: error
  strict: error
  no-useless-ternary: error
