version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:12

    steps:
      - checkout

      - run: yarn install
      - run: yarn run lint

      - save_cache:
          paths:
            - node_modules
          key: js-sdk-dependencies-{{ checksum "package.json" }}

  # build on node 8
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout

      # restore `npm` dependencies cache
      - restore_cache:
          keys:
            - js-sdk-dependencies-{{ checksum "package.json" }}

      # build bundles
      - run: yarn run rollup

  # test on node 8
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout

      # restore `npm` dependencies cache
      - restore_cache:
          keys:
            - js-sdk-dependencies-{{ checksum "package.json" }}

      # build bundles
      - run: yarn run rollup

      # run tests
      - run:
          command: yarn run test-output
          environment:
            MOCHA_FILE: test-results/mocha/test-results.xml
          when: always

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  # run `semantic-release` for release, publishing
  release:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout

      # restore `npm` dependencies cache
      - restore_cache:
          keys:
            - js-sdk-dependencies-{{ checksum "package.json" }}

      # build bundles
      - run: yarn run rollup

      # release, publish package
      - run: npx semantic-release

workflows:
  version: 2
  build_test_release:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
      - release:
          filters:
            branches:
              only:
                - master
                - beta
          requires:
            - test
